---

nextcloud_install_base_directory: /var/www/nextcloud.molecule.lan

nextcloud_instande_id: oczgldo770me

nextcloud_database:
  type: mysql
  username: nextcloud
  password: nextcloud
  hostname: database
  port: 3306
  schema: nextcloud
  mysql:
    utf8mb4: true

nextcloud_trusted_domains:
  - nextcloud.molecule.lan
  - nextcloud.molecule.local

nextcloud_password_salt: cpkxiYp1+qP2YQBGHBz+Tyxq5hzK3D
nextcloud_secret: '0Yvgwz56NtIYLL1t6+5DhUuUA1HZCbl7ojaLLOQQMZN4kYM3'

nextcloud_defaults:
  # language:
  #   default: de
  # locale:
  #   default: de_DE
  phone_region: DE

  data_directory: "/var/www/nc_data"

  memcache:
    # local: '\OC\Memcache\APCu'
    # distributed: '\OC\Memcache\Redis'
    # locking: '\OC\Memcache\Redis'
    servers:
      - host: localhost
        port: 11211
        weight: 0
      - host: 127.0.0.1
        port: 11212
        weight: 1

  redis:
      # can also be a unix domain socket: '/tmp/redis.sock'
    - host: 'redis'
      port: 6379

  logging:
    type: 'file'
    file: '/var/log/nextcloud/nextcloud.log'
    logfile_audit: '/var/log/nextcloud/audit.log'
    level: 1

nextcloud_background_jobs:
  type: systemd          # alternative and currently not supported: webcron | ajax , maybe systemd
  daemon: "{{ 'cron' if ansible_os_family | lower == 'debian' else 'cronie' }}"
  state: enabled      # ['enabled', 'disabled']
  cron:
    minute: "*/10"
    hour: ""
    weekday: ""

...
