---

role_name_check: 1

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: database
    image: "bodsch/ansible-debian:11"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - database
    docker_networks:
      - name: nextcloud
        ipam_config:
          - subnet: "10.18.0.0/24"
            gateway: "10.18.0.254"
    networks:
      - name: nextcloud
        ipv4_address: "10.18.0.1"

  - name: instance
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 80:80
    networks:
      - name: nextcloud
        ipv4_address: "10.18.0.3"


provisioner:
  name: ansible
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      deprecation_warnings: true
      stdout_callback: yaml
      gathering: smart
      fact_caching: jsonfile
      fact_caching_timeout: 8640
      fact_caching_connection: ansible_facts

scenario:
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
