---

nextcloud_install_base_directory: /var/www/nextcloud.molecule.lan

nextcloud_instande_id: oczgldo770me

nextcloud_database:
  type: mysql
  username: nextcloud
  password: nextcloud
  hostname: database
  port: 3306
  schema: nextcloud
  mysql:
    utf8mb4: true

nextcloud_trusted_domains:
  - nextcloud.molecule.lan

nextcloud_password_salt: cpkxiYp1+qP2YQBGHBz+Tyxq5hzK3D
nextcloud_secret: '0Yvgwz56NtIYLL1t6+5DhUuUA1HZCbl7ojaLLOQQMZN4kYM3'

nextcloud_defaults:
  # language:
  #   default: de
  #locale:
  #  default: de_DE
  #phone_region: DE

  data_directory: "/var/www/nc_data"

  # memcache:
  #   # local: '\OC\Memcache\APCu'
  #   distributed: '\OC\Memcache\Redis'
  #   locking: '\OC\Memcache\Redis'
  #
  # redis:
  #   - host: 'redis'                                 # can also be a unix domain socket: '/tmp/redis.sock'
  #     port: 6379

  logging:
    type: 'file'
    file: '/var/log/nextcloud/nextcloud.log'
    logfile_audit: '/var/log/nextcloud/audit.log'
    level: 1

...
