---

- name: nextcloud users
  nextcloud_users:
    users: "{{ nextcloud_users }}"
    working_dir: "{{ nextcloud_install_base_directory }}/nextcloud/server"
    owner: "{{ nextcloud_owner }}"

  register: nc_status

...
